version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    container_name: item
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=item-service"
      - "POSTGRES_USER=item-service-user"
      - "POSTGRES_PASSWORD=item-service-password"
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine3.18
    container_name: redis-container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "63791:6379"

  nats:
    image: nats:2.9-alpine3.17
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - nats