version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    container_name: item
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=item-service"
      - "POSTGRES_USER=item-service-user"
      - "POSTGRES_PASSWORD=item-service-password"
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine3.18
    container_name: redis-container
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "63791:6379"